# Generated by Django 5.1.1 on 2024-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
