"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-msf3a!z5z&34)%9mluj#!h=tgyj2uell^0^br&abf*ixnmoh4&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',  # Your application
]

# Custom user model
AUTH_USER_MODEL = 'myapp.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add custom template directories here if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

# URL settings
LOGIN_URL = '/login/'  # Redirects users to login page if not authenticated
LOGIN_REDIRECT_URL = '/'  # Redirects after successful login
LOGOUT_REDIRECT_URL = '/'  # Redirects after logout

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kalakunj',  # Database name
        'USER': 'root',       # MySQL username
        'PASSWORD': 'root',  # MySQL password
        'HOST': 'localhost',  # MySQL is hosted locally
        'PORT': '3306',       # Default MySQL port
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myapp', 'static'),  # Custom static files directory for your app
]

# Media files (uploaded images for profile pictures, designs, etc.)
# Correct way to handle file paths
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# eSewa credentials
ESEWA_MERCHANT_CODE = 'your_merchant_code'

# Khalti credentials
KHALTI_SECRET_KEY = 'your_khalti_secret_key'

# Example (you will need to fill in actual details based on eSewa/Khalti's documentation):
ESEWA_CONFIG = {
    'MERCHANT_ID': 'your_esewa_merchant_id',
    'MERCHANT_SECRET': 'your_esewa_secret_key',
    'PAYMENT_URL': 'https://esewa.com.np/payment',
}

KHALTI_CONFIG = {
    'PUBLIC_KEY': 'your_khalti_public_key',
    'SECRET_KEY': 'your_khalti_secret_key',
    'PAYMENT_URL': 'https://khalti.com/api/v2/payment',
}

# Include any additional configuration based on the payment provider's documentation.
