# Generated by Django 5.1.1 on 2024-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_design_file_url_remove_design_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
