# Generated by Django 5.1.1 on 2024-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_design_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='status',
        ),
        migrations.AlterField(
            model_name='design',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
